/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_fundamentos_alanis.Vista;

import java.awt.event.ActionListener;

/**
 *
 * @author alanisvaleria
 */
public class GUIElegirColor extends javax.swing.JFrame {

    /**
     * Creates new form GUIElegirColor
     */
    public GUIElegirColor(ActionListener controller) {
        initComponents();
        setVisible(true);
        escuchar(controller);
        
    }
    
    public void escuchar(ActionListener controller){
    this.BtnConejo.addActionListener(controller);
    this.BtnOso.addActionListener(controller);
    this.BtnPato.addActionListener(controller);
    this.BtnCiervo.addActionListener(controller);
    this.BtnMenu.addActionListener(controller);}
    
    public String getBtnConejo (){
    return this.BtnConejo.getActionCommand();
    }
    
    public String getBtnOso (){
    return this.BtnOso.getActionCommand();
    }
    
    public String getBtnPato (){
    return this.BtnPato.getActionCommand();
    }
    
    public String getBtnCiervo (){
    return this.BtnCiervo.getActionCommand();
    }
    
    public String getBtnMenu (){
    return this.BtnMenu.getActionCommand();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPato = new javax.swing.JButton();
        BtnCiervo = new javax.swing.JButton();
        BtnConejo = new javax.swing.JButton();
        BtnOso = new javax.swing.JButton();
        BtnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnPato.setActionCommand("Pato");
        BtnPato.setBorderPainted(false);
        BtnPato.setContentAreaFilled(false);
        getContentPane().add(BtnPato, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 230, 80));

        BtnCiervo.setActionCommand("Ciervo");
        BtnCiervo.setBorderPainted(false);
        BtnCiervo.setContentAreaFilled(false);
        getContentPane().add(BtnCiervo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 230, 80));

        BtnConejo.setActionCommand("Conejo");
        BtnConejo.setBorderPainted(false);
        BtnConejo.setContentAreaFilled(false);
        getContentPane().add(BtnConejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 240, 80));

        BtnOso.setActionCommand("Oso");
        BtnOso.setBorderPainted(false);
        BtnOso.setContentAreaFilled(false);
        getContentPane().add(BtnOso, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 220, 80));

        BtnMenu.setActionCommand("Menu");
        BtnMenu.setBorderPainted(false);
        BtnMenu.setContentAreaFilled(false);
        getContentPane().add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elegir sin título.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIElegirColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIElegirColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIElegirColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIElegirColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCiervo;
    private javax.swing.JButton BtnConejo;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnOso;
    private javax.swing.JButton BtnPato;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
