/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_fundamentos_alanis.Vista;

import java.awt.event.ActionListener;

/**
 *
 * @author alanisvaleria
 */
public class GUIInicio extends javax.swing.JFrame {

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio(ActionListener controller) {
        
        initComponents();
        setVisible(true);
        escuchar(controller);
    }
    
    public void escuchar (ActionListener controller){
    this.BtnJugar.addActionListener(controller);
    this.BtnInstrucciones.addActionListener(controller);
    this.BtnHistoria.addActionListener(controller);
    this.BtnCreditos.addActionListener(controller);
    this.BtnSalir.addActionListener(controller);}
    
    public String getBtnJugar(){
    return this.BtnJugar.getActionCommand();
    }
    
    public String getBtnInstrucciones(){
    return this.BtnInstrucciones.getActionCommand();}
    
    public String getBtnHistoria(){
    return this.BtnHistoria.getActionCommand();}
    
    public String getBtnCreditos(){
    return this.BtnCreditos.getActionCommand();}
    
    public String getBtnSalir(){
    return this.BtnSalir.getActionCommand();}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnInstrucciones = new javax.swing.JButton();
        BtnHistoria = new javax.swing.JButton();
        BtnCreditos = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnJugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnInstrucciones.setActionCommand("Instrucciones");
        BtnInstrucciones.setBorderPainted(false);
        BtnInstrucciones.setContentAreaFilled(false);
        BtnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 270, 90));

        BtnHistoria.setActionCommand("Historia");
        BtnHistoria.setBorderPainted(false);
        BtnHistoria.setContentAreaFilled(false);
        BtnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 270, 90));

        BtnCreditos.setActionCommand("Creditos");
        BtnCreditos.setBorderPainted(false);
        BtnCreditos.setContentAreaFilled(false);
        BtnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 270, 90));

        BtnSalir.setActionCommand("Salir");
        BtnSalir.setBorderPainted(false);
        BtnSalir.setContentAreaFilled(false);
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 270, 90));

        BtnJugar.setActionCommand("Jugar");
        BtnJugar.setBorderPainted(false);
        BtnJugar.setContentAreaFilled(false);
        getContentPane().add(BtnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 330, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseg inicial.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -200, -1, 1120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCreditosActionPerformed

    private void BtnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnInstruccionesActionPerformed

    private void BtnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHistoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreditos;
    private javax.swing.JButton BtnHistoria;
    private javax.swing.JButton BtnInstrucciones;
    private javax.swing.JButton BtnJugar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
