/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_fundamentos_alanis.Vista;

import com.mycompany.proyecto_final_fundamentos_alanis.Modelo.Dado;
import com.mycompany.proyecto_final_fundamentos_alanis.Modelo.Turnos;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.OverlayLayout;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author alanisvaleria
 */
public class GUITablero extends javax.swing.JFrame {

    private PanelTablero panelTablero;
    private PanelControles panelControles;
    Dado dado = new Dado();
    Turnos turno = new Turnos();
    private GUIElegirColor gUIElegirColor;

    public GUITablero(ActionListener controlador) {
        initComponents();
        setVisible(true);
        Escuchar(controlador);

        this.panelTablero = new PanelTablero(controlador);
        // Agregar MouseListener al panel donde quieres obtener las coordenadas
        panelTablero.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int x = e.getX();
                int y = e.getY();
                System.out.println("Clic en: (" + x + ", " + y + ")");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnLanzarDado = new javax.swing.JButton();
        JLabelResultado = new javax.swing.JLabel();
        JLabelTurno = new javax.swing.JLabel();
        JLabelBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLanzarDado.setText("LanzarDado");
        BtnLanzarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLanzarDadoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLanzarDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 200, 90));

        JLabelResultado.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        JLabelResultado.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 420, 50));

        JLabelTurno.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        JLabelTurno.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JLabelTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 410, 70));

        JLabelBack.setForeground(new java.awt.Color(255, 255, 255));
        JLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tablero.png"))); // NOI18N
        getContentPane().add(JLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLanzarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLanzarDadoActionPerformed

        dado.LanzarDado();
        int valor = dado.getValor();
        String turno = this.turno.JugadorActual();
        JLabelTurno.setText(turno);
        this.turno.cambiarTurno();

        JLabelResultado.setText("Dado: " + valor);

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLanzarDadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLanzarDado;
    private javax.swing.JLabel JLabelBack;
    private javax.swing.JLabel JLabelResultado;
    private javax.swing.JLabel JLabelTurno;
    // End of variables declaration//GEN-END:variables

    private void Escuchar(ActionListener controller) {
        this.BtnLanzarDado.addActionListener(controller);
    }
}
