/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofundamentos.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Keiron
 */
public class GUIInicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInicio.class.getName());

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio(ActionListener controladorPrincipal) {
        initComponents();
        setVisible(true);
        escuchar(controladorPrincipal);
        inivisible();
    }

    private void escuchar(ActionListener controladorPrincipal) {
        this.BTNJugar.addActionListener(controladorPrincipal);
        this.BTNCreditos.addActionListener(controladorPrincipal);
        this.BTNHistoria.addActionListener(controladorPrincipal);
        this.Instrucciones.addActionListener(controladorPrincipal);
        this.BOTNVERDE.addActionListener(controladorPrincipal);
        this.BotonAmarillo.addActionListener(controladorPrincipal);
        this.BotonAzul.addActionListener(controladorPrincipal);
        this.BotonRojo.addActionListener(controladorPrincipal);
    }

      private void inivisible() {
          
          this.BTNJugar.setOpaque(false);
        this.BTNJugar.setContentAreaFilled(false);
        this.BTNJugar.setBorderPainted(false);
        this.BTNJugar.setFocusPainted(false);
        
        this.BTNHistoria.setOpaque(false);
        this.BTNHistoria.setContentAreaFilled(false);
        this.BTNHistoria.setBorderPainted(false);
        this.BTNHistoria.setFocusPainted(false);
        
        this.BTNCreditos.setOpaque(false);
        this.BTNCreditos.setContentAreaFilled(false);
        this.BTNCreditos.setBorderPainted(false);
        this.BTNCreditos.setFocusPainted(false);
        
        this.Instrucciones.setOpaque(false);
        this.Instrucciones.setContentAreaFilled(false);
        this.Instrucciones.setBorderPainted(false);
        this.Instrucciones.setFocusPainted(false);
        
        this.BotonAmarillo.setOpaque(false);
        this.BotonAmarillo.setContentAreaFilled(false);
        this.BotonAmarillo.setBorderPainted(false);
        this.BotonAmarillo.setFocusPainted(false);

        this.BOTNVERDE.setOpaque(false);
        this.BOTNVERDE.setContentAreaFilled(false);
        this.BOTNVERDE.setBorderPainted(false);
        this.BOTNVERDE.setFocusPainted(false);
        
        this.BotonAzul.setOpaque(false);
        this.BotonAzul.setContentAreaFilled(false);
        this.BotonAzul.setBorderPainted(false);
        this.BotonAzul.setFocusPainted(false);
        
        this.BotonRojo.setOpaque(false);
        this.BotonRojo.setContentAreaFilled(false);
        this.BotonRojo.setBorderPainted(false);
        this.BotonRojo.setFocusPainted(false);
    }
    public String getBtnPlay() {
        return this.BTNJugar.getActionCommand();
    }

    public String getBtnHistoria() {
        return this.BTNHistoria.getActionCommand();
    }

    public String getBtnCreditos() {
        return this.BTNCreditos.getActionCommand();
    }

    public String getBtnInstrucciones() {
        return this.Instrucciones.getActionCommand();
    }

    public String getColorAzul() {
        return this.BotonAzul.getActionCommand();
    }

    public String getColorAmarillo() {
        return this.BotonAmarillo.getActionCommand();
    }

    public String getColorVerde() {
        return this.BOTNVERDE.getActionCommand();
    }

    public String getColorRojo() {
        return this.BotonRojo.getActionCommand();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNJugar = new javax.swing.JButton();
        BTNHistoria = new javax.swing.JButton();
        Instrucciones = new javax.swing.JButton();
        BTNCreditos = new javax.swing.JButton();
        BotonAzul = new javax.swing.JButton();
        BOTNVERDE = new javax.swing.JButton();
        BotonAmarillo = new javax.swing.JButton();
        BotonRojo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PARCHIS - OPTIONS");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNJugar.setForeground(new java.awt.Color(255, 255, 255));
        BTNJugar.setText("JUGAR");
        BTNJugar.setActionCommand("BtnJugar");
        BTNJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNJugarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 50, 90, 70));

        BTNHistoria.setForeground(new java.awt.Color(255, 255, 255));
        BTNHistoria.setText("Historia");
        BTNHistoria.setActionCommand("BTNHISTORIA");
        BTNHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(BTNHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 90, 70));

        Instrucciones.setForeground(new java.awt.Color(255, 255, 255));
        Instrucciones.setText("Instrucciones");
        Instrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(Instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 90, 60));

        BTNCreditos.setForeground(new java.awt.Color(255, 255, 255));
        BTNCreditos.setText("Creditos");
        getContentPane().add(BTNCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 90, 70));

        BotonAzul.setForeground(new java.awt.Color(255, 255, 255));
        BotonAzul.setText("Azul");
        BotonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAzulActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 80, 80));

        BOTNVERDE.setForeground(new java.awt.Color(255, 255, 255));
        BOTNVERDE.setText("Verde");
        getContentPane().add(BOTNVERDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 80, 80));

        BotonAmarillo.setForeground(new java.awt.Color(255, 255, 255));
        BotonAmarillo.setText("Amarillo");
        BotonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAmarilloActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 80, 80));

        BotonRojo.setForeground(new java.awt.Color(255, 255, 255));
        BotonRojo.setText("Rojo");
        getContentPane().add(BotonRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 80, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2025-10-16 at 4.00.22 PM-convertido-a-mediano.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNJugarActionPerformed
    }//GEN-LAST:event_BTNJugarActionPerformed

    private void InstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstruccionesActionPerformed

    private void BotonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAmarilloActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_BotonAmarilloActionPerformed

    private void BTNHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHistoriaActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_BTNHistoriaActionPerformed

    private void BotonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTNVERDE;
    private javax.swing.JButton BTNCreditos;
    private javax.swing.JButton BTNHistoria;
    private javax.swing.JButton BTNJugar;
    private javax.swing.JButton BotonAmarillo;
    private javax.swing.JButton BotonAzul;
    private javax.swing.JButton BotonRojo;
    private javax.swing.JButton Instrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
